---
- name: Initialize and Sync dotfiles with chezmoi
  ansible.builtin.command: chezmoi init --apply --source {{ dotfiles_repo }}
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.local/share/chezmoi"
  become: true
  become_user: "{{ ansible_user }}"
